# Numpy Learn

In [1]:
import numpy as np


In [2]:
a=[3,54,5,5,]
data = np.array([a])
print(data)
print(data[0,1])

[[ 3 54  5  5]]
54


In [3]:
# chack shape
data.shape 

(1, 4)

In [4]:
# chack type
data.dtype

dtype('int32')

In [5]:
# create zeroes Matrix

ZM = np.zeros((5,10))
print(ZM)
print(ZM.dtype)
# print(ZM[1,6])
ZM.shape

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
float64


(5, 10)

In [6]:
# create the np list With auto arange
AM = np.arange(16)
AM

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [7]:
# Create linearly space list 
LS = np.linspace(1,20,5)
LS

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [8]:
# create randem Matrix.
emp = np.empty((2,10))
print(emp)
print(emp.shape)

[[ 0.00000000e+000  0.00000000e+000  0.00000000e+000  0.00000000e+000
   0.00000000e+000  0.00000000e+000  0.00000000e+000  0.00000000e+000
   0.00000000e+000 -1.14084259e-310]
 [ 3.16202013e-322  9.61026157e-312  9.61026158e-312  7.90505033e-323
   8.48798316e-314              nan  3.23625578e-310  7.90505033e-323
   6.67462976e-067  0.00000000e+000]]
(2, 10)


In [9]:
# create the copy of an Matrix & List
EL= np.empty_like(emp)
EL

array([[3.56043053e-307, 1.60219306e-306, 7.56571288e-307,
        1.89146896e-307, 1.37961302e-306, 1.05699242e-307,
        8.01097889e-307, 1.78020169e-306, 7.56601165e-307,
        1.02359984e-306],
       [1.33510679e-306, 2.22522597e-306, 1.33511018e-306,
        6.23057689e-307, 1.29061821e-306, 8.34449382e-308,
        1.33508761e-307, 1.33511562e-306, 8.90103560e-307,
        1.42410974e-306]])

In [10]:
# Create an identity or MAtrix like (2x2 ,3x3, 4x4,....)
ID = np.identity(6)
ID

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [14]:
# List in to MAtrix trick & Matrix into list
List = np.arange(2,52)
print(List.shape)
print(List,' \nList\n')


Matrix = List.reshape(5,10)
print(Matrix.shape)
print(Matrix,' \nInto MAtrix\n ')

ravel = Matrix.ravel()
print(ravel.shape)
print(ravel,' \nInto List\n')


(50,)
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
 50 51]  
List

(5, 10)
[[ 2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21]
 [22 23 24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48 49 50 51]]  
Into MAtrix
 
(50,)
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
 50 51]  
Into List



In [15]:
# Sum of the All Rows And Columns (axis)
Mat = [[1,2,3],[4,5,6],[0,4,1]]

a = np.array(Mat)
print(a,'\n')

axisR = a.sum(axis = 0)
print(axisR,'\n')

axisC = a.sum(axis = 1)
print(axisC,'\n')


[[1 2 3]
 [4 5 6]
 [0 4 1]] 

[ 5 11 10] 

[ 6 15  5] 



In [16]:
# Transpose of the matrix
t = a.T
print(a,"\n")
print(t)

[[1 2 3]
 [4 5 6]
 [0 4 1]] 

[[1 4 0]
 [2 5 4]
 [3 6 1]]


In [17]:
# chack dimension of the matrix
print(a.ndim)


2


In [18]:
# print all the numbers of matrix indugly 
ind  = t.flat
print(ind)

for items in ind:
    print(items)

1
4
0
2
5
4
3
6
1


In [19]:
# Find allnumbers of RxC in matrix or List
print(ZM.size)

50


In [20]:
# chack the bytes
print(ZM.nbytes)

400


In [21]:
# Fint max number in list
aa  = np.array([4,6,1,4,7,0,3,2])
bb = aa.argmax()
print (aa)
print(bb,': index \n')
print(aa[bb], ': index value ')

# Fint min number in list
bb = aa.argmin()
print (aa)
print(bb,': index \n')
print(aa[bb], ': index value ')

[4 6 1 4 7 0 3 2]
4 : index 

7 : index value 
[4 6 1 4 7 0 3 2]
5 : index 

0 : index value 


In [22]:
# Fint min number in Matrix
print (a)
# print(a[1][1])
MM=a.argmin()

print(MM,': index \n')
# print(a([1][MM]), ': index value ')

# Fint mix number in Matrix

MN=a.argmax()

print(MN,': index \n')






[[1 2 3]
 [4 5 6]
 [0 4 1]]
6 : index 

5 : index 



In [23]:

# Fint min number in Matrix with axes
print(a)

MA=a.argmin(axis = 0)

print(MA,': index R \n')

MNA=a.argmin(axis = 1)

print(MNA,': index C \n')


# Fint max number in Matrix with axes

MA=a.argmax(axis = 0)

print(MA,': index R \n')

MNA=a.argmax(axis = 1)

print(MNA,': index C \n')



[[1 2 3]
 [4 5 6]
 [0 4 1]]
[2 0 2] : index R 

[0 0 0] : index C 

[1 1 1] : index R 

[2 2 1] : index C 



In [30]:
# sort the row-wise values and show the indexs

print(a)
sar = a.argsort(axis = 0)
print('sort index values Row-wise\n',sar)


sac = a.argsort(axis = 1)
print('sort index values column-wise\n',sac)

[[1 2 3]
 [4 5 6]
 [0 4 1]]
<built-in method flatten of numpy.ndarray object at 0x000001C4E3EE5F30>
sort index values Row-wise
 [[2 0 2]
 [0 2 0]
 [1 1 1]]
sort index values column-wise
 [[0 1 2]
 [0 1 2]
 [0 2 1]]
